<<<<<<< HEAD
version: '3'

services:
  backend-srpu-local:
    build: .
    environment:
      SRPU_B_APP_DB_HOST: "10.200.4.161"
      SRPU_B_APP_DB_USER: "root"
      SRPU_B_APP_DB_DATABASE: "SRPU"
      SRPU_B_APP_DB_PASSWORD: "xQRA0xBC87Gs"
      SRPU_B_APP_PORT: "3500"
      SRPU_B_APP_JWT_SECRET_KEY: "2A95F5CCD11DE255FEE9451BDE433"
      SRPU_B_APP_TOKEN_HEADER_KEY: "authorization"
      SRPU_B_APP_REFRESH_TOKEN_KEY: "4ebd020883285d698c44ec50939c8567" 
      SRPU_B_APP_EMAIL_USER: "noreply.cecapmex@gmail.com"
      SRPU_B_APP_EMAIL_PASSWORD: "hpffapcifkvkfuey"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3500:3000
      - 9229:9229
    restart: always
=======
version: "3"

services:
  front-siednl:
    container_name: front-srpu
    image: front-srpu
    build:
      context: .
    environment:
      REACT_APP_APPLICATION_BACK : http://10.200.4.105:3500
      REACT_APP_APPLICATION_LOGIN : http://10.200.4.105:5000
      REACT_APP_APPLICATION_LOGIN_FRONT : http://10.200.4.106/
      REACT_APP_APPLICATION_MID : http://10.200.4.164:9093
      REACT_APP_APPLICATION_FILES : http://10.200.4.105:90
      REACT_APP_APPLICATION_FIRMA : http://10.200.4.105:8500
      REACT_APP_APPLICATION_CORREO : http://10.200.4.105:8001
      REACT_APP_APPLICATION_FIEL : http://10.200.4.105:8081
      REACT_APP_APPLICATION_FIRMADOC : http://10.200.4.105:9091
      REACT_APP_APPLICATION_RUTA_ARCHIVOS_CORTOPLAZO : /SRPU/CORTOPLAZO
      REACT_APP_APPLICATION_ENVIRONMENT : LOCAL
      REACT_APP_APPLICATION_VERSION : 1.0.0

    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
>>>>>>> d8c8267a4ea3a4f6d8fc4e1e17c2b88788077983
