version: "3"

services:
  front-siednl:
    container_name: front-srpu
    image: front-srpu
    build:
      context: .
    environment:
      REACT_APP_APPLICATION_BACK : http://10.200.4.105:3500
      REACT_APP_APPLICATION_LOGIN : http://10.200.4.105:5000
      REACT_APP_APPLICATION_LOGIN_FRONT : http://10.200.4.106/
      REACT_APP_APPLICATION_MID : http://10.200.4.105:9093
      REACT_APP_APPLICATION_FILES : http://10.200.4.105:90
      REACT_APP_APPLICATION_FIRMA : http://10.200.4.105:8500
      REACT_APP_APPLICATION_CORREO : http://10.200.4.105:8001
      REACT_APP_APPLICATION_FIEL : http://10.200.4.105:8081
      REACT_APP_APPLICATION_FIRMADOC : http://10.200.4.105:9091
      REACT_APP_APPLICATION_RUTA_ARCHIVOS_CORTOPLAZO : /SRPU/CORTOPLAZO
      REACT_APP_APPLICATION_ENVIRONMENT : LOCAL
      REACT_APP_APPLICATION_VERSION : 1.0.0

    volumes:
      - ./src:/app/src
    ports:
      - 4500:3000