version: "3"

services:
  front-siednl:
    container_name: front-srpu
    image: front-srpu
    build:
      context: .
    environment:
      REACT_APP_APPLICATION_BACK: https://tesoreria-virtual-servicios.nl.gob.mx/api/srpu
      REACT_APP_APPLICATION_LOGIN: http://tesoreria-virtual-servicios.nl.gob.mx
      REACT_APP_APPLICATION_LOGIN_FRONT: https://tesoreria-virtual.nl.gob.mx/
      REACT_APP_APPLICATION_MID: http://tesoreria-virtual-servicios.nl.gob.mx/api/mid
      REACT_APP_APPLICATION_FILES: http://tesoreria-virtual-servicios.nl.gob.mx

      REACT_APP_APPLICATION_FIRMA: http://tesoreria-virtual-servicios.nl.gob.mx/ApiValidaCers
      REACT_APP_APPLICATION_CORREO: http://tesoreria-virtual-servicios.nl.gob.mx/correos
      REACT_APP_APPLICATION_FIEL: http://tesoreria-virtual-servicios.nl.gob.mx/ApiSatFirma
      REACT_APP_APPLICATION_FIRMADOC: http://tesoreria-virtual-servicios.nl.gob.mx/ApiGeneraDocumentos

      REACT_APP_APPLICATION_RUTA_ARCHIVOS_CORTOPLAZO: /SRPU/CORTOPLAZO
      REACT_APP_DOC_ROUTE: /SRPU_PROD
      REACT_APP_APPLICATION_ENVIRONMENT: PROD
      REACT_APP_APPLICATION_VERSION: 1.0.0

    volumes:
      - ./src:/app/src
    ports:
      - 4500:3000
